### GET BOOKS
GET http://localhost:5000/books HTTP/1.1

### GET SINGLE BOOK
GET http://localhost:5000/books/3 HTTP/1.1

### ADD SINGLE BOOK
POST http://localhost:5000/books HTTP/1.1
Content-Type: application/json

{
    "title": "Awaken the Giant Within",
    "author": "Tony Robbins",
    "published": "12/30/2016"
}